/*
 * Copyright 2022 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *   Licensed under the Apache License, Version 2.0 (the "License").
 *   You may not use this file except in compliance with the License.
 *   A copy of the License is located at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   or in the "license" file accompanying this file. This file is distributed
 *   on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 *   express or implied. See the License for the specific language governing
 *   permissions and limitations under the License.
 */

package software.amazon.disco.instrumentation.preprocess.multipreprocessor;

import lombok.Builder;
import lombok.Getter;

/**
 * Pojo corresponding to outcome of a preprocessor.
 */
@Getter
@Builder
public class PreprocessorOutcome {
    /**
     * Exit value of the preprocessor, the value 0 indicates normal termination.
     */
    private int exitCode;
    /**
     * Output of the preprocessor, standard output combined with error output generated by processes.
     */
    private String preprocessorOutput;
    /**
     * Command-line arguments passed to the preprocessor;
     */
    private String[] commandlineArgs;
}